import "@/styles/global.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className=" min-h-screen bg-slate-800">

        {children}

      </body>
    </html>
  )
}
