import "@/styles/global.css";
import PageFooter from "@/components/index/footer/PageFooter"
import PageHeader from "@/components/index/header/PageHeader"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className=" min-h-screen bg-slate-800">
        <PageHeader />

        {children}

        <PageFooter />
      </body>
    </html>
  )
}
